version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./:/hassan-web
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build: .
        volumes:
            - ./:/hassan-web
        networks:
            - code-network

    db:
        image: mysql:8.0
        container_name: mysq_server
        restart: always
        volumes:
           - .data/:/var/lib/mysql
        ports:
           - '6603:3306'
        environment:
           MYSQL_ROOT_PASSWORD: 123

    app:
        depends_on:
           - db
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
           - '80:80'
        environment:
           PMA_HOST: db

networks:
    code-network:
        driver: bridge
