version: '3'

services:
    php:
        build: .
        volumes:
            - ./:/hassan-web

    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./:/hassan-web
            - ./site.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    db:
        image: mysql:8.0
        container_name: db
        restart: always
        volumes:
           - .data/:/var/lib/mysql
        ports:
           - '6603:3306'
        depends_on:
           - php
        environment:
           MYSQL_ROOT_PASSWORD: 123

    app:
        depends_on:
           - db
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
           - '80:80'
        environment:
           PMA_HOST: db
